import {
  mdiAccount,
  mdiAccountGroup,
  mdiAirConditioner,
  mdiAlert,
  mdiAlertCircle,
  mdiBabyCarriage,
  mdiBagPersonal,
  mdiBathtub,
  mdiBattery,
  mdiBatteryCharging,
  mdiBeach,
  mdiBed,
  mdiBedDouble,
  mdiBedKing,
  mdiBell,
  mdiBellRing,
  mdiBicycle,
  mdiBlenderOutline,
  mdiBlinds,
  mdiBlindsOpen,
  mdiBookOpenPageVariant,
  mdiBookshelf,
  mdiBunkBed,
  mdiCalendar,
  mdiCamera,
  mdiCar,
  mdiCarElectric,
  mdiCast,
  mdiCctv,
  mdiCeilingLight,
  mdiCeilingLightOutline,
  mdiChairRolling,
  mdiCheckCircle,
  mdiCityVariant,
  mdiClockOutline,
  mdiCoachLamp,
  mdiCoatRack,
  mdiCoffeeMaker,
  mdiController,
  mdiCountertop,
  mdiDesk,
  mdiDeskLamp,
  mdiDesktopTower,
  mdiDishwasher,
  mdiDomain,
  mdiDoor,
  mdiDoorClosed,
  mdiDoorOpen,
  mdiDoorbell,
  mdiDresser,
  mdiEvStation,
  mdiExitRun,
  mdiEye,
  mdiFan,
  mdiFanOff,
  mdiFence,
  mdiFlash,
  mdiFlashOutline,
  mdiFloorLamp,
  mdiFloorPlan,
  mdiFlower,
  mdiFridge,
  mdiFridgeOutline,
  mdiGamepadVariant,
  mdiGarage,
  mdiGarageOpen,
  mdiGarageOpenVariant,
  mdiGarageVariant,
  mdiGasStation,
  mdiGlassCocktail,
  mdiGrass,
  mdiGrill,
  mdiHammerWrench,
  mdiHanger,
  mdiHeart,
  mdiHelpCircle,
  mdiHome,
  mdiHomeOutline,
  mdiHomeVariant,
  mdiInformation,
  mdiIron,
  mdiLamp,
  mdiLaptop,
  mdiLedStrip,
  mdiLedStripVariant,
  mdiLedStripVariantOff,
  mdiLightbulb,
  mdiLightbulbGroup,
  mdiLightbulbOff,
  mdiLightbulbOn,
  mdiLightbulbOutline,
  mdiLock,
  mdiLockOpen,
  mdiLockOpenVariant,
  mdiMicrowave,
  mdiMirror,
  mdiMonitor,
  mdiMoonWaningCrescent,
  mdiMotionSensor,
  mdiMotorbike,
  mdiMovie,
  mdiMovieOpen,
  mdiMusic,
  mdiNaturePeople,
  mdiNetworkOutline,
  mdiOfficeBuilding,
  mdiPalette,
  mdiPaletteOutline,
  mdiPalmTree,
  mdiPause,
  mdiPineTree,
  mdiPlay,
  mdiPool,
  mdiPotSteam,
  mdiPower,
  mdiPowerOff,
  mdiPowerOn,
  mdiPowerPlug,
  mdiPowerPlugOff,
  mdiPowerSocket,
  mdiPowerSocketEu,
  mdiPowerSocketUs,
  mdiPrinter,
  mdiRadiator,
  mdiRobotVacuum,
  mdiRouterWireless,
  mdiRunFast,
  mdiSchool,
  mdiScript,
  mdiScriptText,
  mdiSeat,
  mdiSeatReclineNormal,
  mdiServer,
  mdiShieldCheck,
  mdiShieldHome,
  mdiShower,
  mdiShowerHead,
  mdiSilverwareForkKnife,
  mdiSkipNext,
  mdiSkipPrevious,
  mdiSleep,
  mdiSleepOff,
  mdiSmokeDetector,
  mdiSmokeDetectorVariant,
  mdiSofa,
  mdiSolarPower,
  mdiSpeaker,
  mdiSpeakerWireless,
  mdiSprinkler,
  mdiSprinklerVariant,
  mdiStairs,
  mdiStairsBox,
  mdiStar,
  mdiStop,
  mdiStove,
  mdiSunWireless,
  mdiSunglasses,
  mdiTableFurniture,
  mdiTeddyBear,
  mdiTelevision,
  mdiTheater,
  mdiThermometer,
  mdiThermometerLines,
  mdiThermostat,
  mdiTimerOutline,
  mdiToaster,
  mdiToggleSwitch,
  mdiToggleSwitchOff,
  mdiToilet,
  mdiTools,
  mdiTree,
  mdiTumbleDryer,
  mdiVolumeHigh,
  mdiVolumeOff,
  mdiWallSconceRound,
  mdiWardrobe,
  mdiWarehouse,
  mdiWashingMachine,
  mdiWashingMachineAlert,
  mdiWashingMachineOff,
  mdiWater,
  mdiWaterBoiler,
  mdiWaterPercent,
  mdiWaterPump,
  mdiWeatherCloudy,
  mdiWeatherNight,
  mdiWeatherRainy,
  mdiWeatherSunny,
  mdiWeatherSunset,
  mdiWeatherSunsetDown,
  mdiWeatherSunsetUp,
  mdiWeightLifter,
  mdiWhiteBalanceSunny,
  mdiWifi,
  mdiWindowClosed,
  mdiWindowOpen,
  mdiWindowShutter,
  mdiWrench,
} from '@mdi/js'

// Curated, because HA hands out icon names at runtime (`mdi:sofa`) and importing the whole
// MDI set to look them up would put thousands of paths in the bundle. Keys are bare names.
const HA_ICONS: Record<string, string> = {
  sofa: mdiSofa,
  bed: mdiBed,
  'bed-king': mdiBedKing,
  'bed-double': mdiBedDouble,
  bathtub: mdiBathtub,
  'shower-head': mdiShowerHead,
  shower: mdiShower,
  toilet: mdiToilet,
  desk: mdiDesk,
  countertop: mdiCountertop,
  'table-furniture': mdiTableFurniture,
  'coat-rack': mdiCoatRack,
  garage: mdiGarage,
  'garage-variant': mdiGarageVariant,
  'garage-open': mdiGarageOpen,
  'garage-open-variant': mdiGarageOpenVariant,
  stairs: mdiStairs,
  'stairs-box': mdiStairsBox,
  'washing-machine': mdiWashingMachine,
  'water-boiler': mdiWaterBoiler,
  'weight-lifter': mdiWeightLifter,
  television: mdiTelevision,
  'glass-cocktail': mdiGlassCocktail,
  school: mdiSchool,
  grill: mdiGrill,
  'coach-lamp': mdiCoachLamp,
  'wall-sconce-round': mdiWallSconceRound,
  'nature-people': mdiNaturePeople,
  home: mdiHome,
  'home-outline': mdiHomeOutline,
  'home-variant': mdiHomeVariant,
  door: mdiDoor,
  'door-open': mdiDoorOpen,
  'door-closed': mdiDoorClosed,
  'window-shutter': mdiWindowShutter,
  'window-closed': mdiWindowClosed,
  'window-open': mdiWindowOpen,
  blinds: mdiBlinds,
  'blinds-open': mdiBlindsOpen,
  radiator: mdiRadiator,
  'air-conditioner': mdiAirConditioner,
  'robot-vacuum': mdiRobotVacuum,
  lightbulb: mdiLightbulb,
  'lightbulb-outline': mdiLightbulbOutline,
  'lightbulb-group': mdiLightbulbGroup,
  'lightbulb-on': mdiLightbulbOn,
  'lightbulb-off': mdiLightbulbOff,
  lamp: mdiLamp,
  'floor-lamp': mdiFloorLamp,
  'desk-lamp': mdiDeskLamp,
  'ceiling-light': mdiCeilingLight,
  'ceiling-light-outline': mdiCeilingLightOutline,
  'led-strip': mdiLedStrip,
  'led-strip-variant': mdiLedStripVariant,
  'led-strip-variant-off': mdiLedStripVariantOff,
  fan: mdiFan,
  'fan-off': mdiFanOff,
  'power-plug': mdiPowerPlug,
  'power-plug-off': mdiPowerPlugOff,
  'power-socket': mdiPowerSocket,
  'power-socket-us': mdiPowerSocketUs,
  'power-socket-eu': mdiPowerSocketEu,
  speaker: mdiSpeaker,
  'speaker-wireless': mdiSpeakerWireless,
  cast: mdiCast,
  thermostat: mdiThermostat,
  lock: mdiLock,
  'lock-open': mdiLockOpen,
  'lock-open-variant': mdiLockOpenVariant,
  theater: mdiTheater,
  'silverware-fork-knife': mdiSilverwareForkKnife,
  stove: mdiStove,
  fridge: mdiFridge,
  'fridge-outline': mdiFridgeOutline,
  microwave: mdiMicrowave,
  dishwasher: mdiDishwasher,
  'coffee-maker': mdiCoffeeMaker,
  'blender-outline': mdiBlenderOutline,
  toaster: mdiToaster,
  'tumble-dryer': mdiTumbleDryer,
  iron: mdiIron,
  'washing-machine-alert': mdiWashingMachineAlert,
  sprinkler: mdiSprinkler,
  'sprinkler-variant': mdiSprinklerVariant,
  flower: mdiFlower,
  tree: mdiTree,
  'pine-tree': mdiPineTree,
  'palm-tree': mdiPalmTree,
  fence: mdiFence,
  pool: mdiPool,
  beach: mdiBeach,
  'pot-steam': mdiPotSteam,
  grass: mdiGrass,
  'floor-plan': mdiFloorPlan,
  'bunk-bed': mdiBunkBed,
  'baby-carriage': mdiBabyCarriage,
  'teddy-bear': mdiTeddyBear,
  'gamepad-variant': mdiGamepadVariant,
  controller: mdiController,
  laptop: mdiLaptop,
  monitor: mdiMonitor,
  'desktop-tower': mdiDesktopTower,
  printer: mdiPrinter,
  'router-wireless': mdiRouterWireless,
  wifi: mdiWifi,
  server: mdiServer,
  'network-outline': mdiNetworkOutline,
  'chair-rolling': mdiChairRolling,
  'seat-recline-normal': mdiSeatReclineNormal,
  seat: mdiSeat,
  bookshelf: mdiBookshelf,
  'book-open-page-variant': mdiBookOpenPageVariant,
  wardrobe: mdiWardrobe,
  dresser: mdiDresser,
  hanger: mdiHanger,
  mirror: mdiMirror,
  'washing-machine-off': mdiWashingMachineOff,
  car: mdiCar,
  'car-electric': mdiCarElectric,
  bicycle: mdiBicycle,
  motorbike: mdiMotorbike,
  warehouse: mdiWarehouse,
  tools: mdiTools,
  'hammer-wrench': mdiHammerWrench,
  wrench: mdiWrench,
  'office-building': mdiOfficeBuilding,
  domain: mdiDomain,
  'city-variant': mdiCityVariant,
  flash: mdiFlash,
  'flash-outline': mdiFlashOutline,
  battery: mdiBattery,
  'battery-charging': mdiBatteryCharging,
  'solar-power': mdiSolarPower,
  'ev-station': mdiEvStation,
  'gas-station': mdiGasStation,
  water: mdiWater,
  'water-percent': mdiWaterPercent,
  'water-pump': mdiWaterPump,
  thermometer: mdiThermometer,
  'thermometer-lines': mdiThermometerLines,
  'weather-sunny': mdiWeatherSunny,
  'weather-night': mdiWeatherNight,
  'weather-cloudy': mdiWeatherCloudy,
  'weather-rainy': mdiWeatherRainy,
  'white-balance-sunny': mdiWhiteBalanceSunny,
  'moon-waning-crescent': mdiMoonWaningCrescent,
  'sun-wireless': mdiSunWireless,
  eye: mdiEye,
  'shield-home': mdiShieldHome,
  'shield-check': mdiShieldCheck,
  cctv: mdiCctv,
  camera: mdiCamera,
  doorbell: mdiDoorbell,
  bell: mdiBell,
  'bell-ring': mdiBellRing,
  'motion-sensor': mdiMotionSensor,
  'smoke-detector': mdiSmokeDetector,
  'smoke-detector-variant': mdiSmokeDetectorVariant,
  'movie-open': mdiMovieOpen,
  movie: mdiMovie,
  music: mdiMusic,
  play: mdiPlay,
  pause: mdiPause,
  stop: mdiStop,
  'skip-next': mdiSkipNext,
  'skip-previous': mdiSkipPrevious,
  'volume-high': mdiVolumeHigh,
  'volume-off': mdiVolumeOff,
  power: mdiPower,
  'power-on': mdiPowerOn,
  'power-off': mdiPowerOff,
  'toggle-switch': mdiToggleSwitch,
  'toggle-switch-off': mdiToggleSwitchOff,
  'script-text': mdiScriptText,
  script: mdiScript,
  palette: mdiPalette,
  'palette-outline': mdiPaletteOutline,
  star: mdiStar,
  heart: mdiHeart,
  'clock-outline': mdiClockOutline,
  'timer-outline': mdiTimerOutline,
  calendar: mdiCalendar,
  information: mdiInformation,
  alert: mdiAlert,
  'alert-circle': mdiAlertCircle,
  'check-circle': mdiCheckCircle,
  'help-circle': mdiHelpCircle,
  sleep: mdiSleep,
  'sleep-off': mdiSleepOff,
  'weather-sunset': mdiWeatherSunset,
  'weather-sunset-up': mdiWeatherSunsetUp,
  'weather-sunset-down': mdiWeatherSunsetDown,
  account: mdiAccount,
  'account-group': mdiAccountGroup,
  'exit-run': mdiExitRun,
  'run-fast': mdiRunFast,
  'bag-personal': mdiBagPersonal,
  sunglasses: mdiSunglasses,
}

const MDI_PREFIX = 'mdi:'

// Resolves an HA icon string to a path, or `fallback` for anything unknown: other prefixes
// (`hass:`), empty values, and names outside the curated map.
export function iconForHa(name: string | undefined, fallback: string): string {
  if (!name?.startsWith(MDI_PREFIX)) return fallback
  const key = name.slice(MDI_PREFIX.length)
  return Object.hasOwn(HA_ICONS, key) ? HA_ICONS[key] : fallback
}
